[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[variables]
NODE_ENV = "production"
NITRO_HOST = "0.0.0.0"
PORT = "3000"

[start]
cmd = "npm run start"
